### PR TITLE
Gist and Codepen shortcode

### PR DESCRIPTION
**Pull request by noxify**
* Added new inline parser for GitHub gists and codepen
* reordered the use part ( I love this step structure :) )
* added missing parsers in the service provider

Here my work from the weekend :)
Hope you like it :)

### CODE REVIEW

**Comment by noxify** [comment]
forgot the tests.. i'm working on it :)

**Comment by johnnyhuy** [comment]
Awesome work once again! Can we get some docs on the new parsers?

If anything, I can get it up to date later this week 😀

**Comment by noxify** [comment]
@johnnyhuy - Sure - I will add some inline docs.
Are the unit tests enough?

**Comment by johnnyhuy** [comment]
Yep unit tests are good enough, as long as the tests represent the intended feature 🙂

**Comment by noxify** [comment]
@johnnyhuy today i found the time to add some inline docs.
I did it also for the existing block elements.

Is this the documentation which you expected? 

Btw. i have no clue why the travis job failed. It seems that something went wront on Travis CI side: https://travis-ci.com/johnnyhuy/laravel-useful-commonmark-extension/builds/94547451

**Comment by johnnyhuy** [comment]
That's all good, I'll merge it in thanks again

I've bumped up the release to v1.1.4 expect to see changes there 🙂

**Pull request merged**
